#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Please read README.md
Generated by deepSeek v4.1-Flash
Verified and tested by ELXT
"""

VERSION='v1.1 -20261004'

import argparse
import os
import posixpath
import re
import sys
import tempfile
import zipfile
from collections import OrderedDict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
try:
    import rwmod_tool as rt
except ImportError:
    sys.stderr.write(
        "error: rwmod_tool.py must sit next to rwmod_decompile.py\n")
    raise SystemExit(2)


# --------------------------------------------------------------------------
# Character cleanup (anti-obfuscation)
# --------------------------------------------------------------------------

# Format / directional / variation-selector / private-use characters that
# packers sprinkle over member names and ini content.  U+E0000..U+E0FFF also
# covers the supplementary variation selectors (U+E0100..U+E01EF).
INVISIBLE_RE = re.compile(
    "[\u00ad\u061c\u180e"
    "\u200b-\u200f"           # zero width + directional marks
    "\u202a-\u202e"           # embedding / override
    "\u2060-\u206f"           # word joiner, invisible operators, isolates
    "\ufeff\ufff9-\ufffb"
    "\ufe00-\ufe0f"           # variation selectors
    "\U000e0000-\U000e0fff]"  # tag block + supplementary PUA
)
CONTROL_RE = re.compile("[\u0000-\u001f\u007f-\u009f]")


def clean_text(text):
    """Drop invisible / private-use / control filler from a string."""
    return CONTROL_RE.sub("", INVISIBLE_RE.sub("", text))


def escaped_name(name):
    """Rewrite invisible characters as visible "xXXXX_" atoms.

    Unlike plain removal this keeps different obfuscated names distinct, so
    a file whose name carries no other information still gets a unique,
    eyeball-readable fallback name.
    """
    out = []
    for ch in name:
        if INVISIBLE_RE.match(ch) or CONTROL_RE.match(ch):
            out.append("x%04x_" % ord(ch))
        else:
            out.append(ch)
    return "".join(out)


_BAD_FS_CHARS = re.compile(r'[\\/:*?"<>|\u0000-\u001f]')
_RESERVED_NAMES = frozenset(
    ["CON", "PRN", "AUX", "NUL"]
    + ["COM%d" % i for i in range(1, 10)]
    + ["LPT%d" % i for i in range(1, 10)])


def sanitize_stem(text, fallback="file"):
    """Make a filesystem-safe file stem out of arbitrary config text."""
    stem = _BAD_FS_CHARS.sub("_", clean_text(text))
    stem = re.sub(r"\s+", "_", stem).strip("._ ")
    if len(stem) > 80:
        stem = stem[:80].rstrip("._ ")
    if not stem:
        stem = fallback
    if stem.split(".")[0].upper() in _RESERVED_NAMES:
        stem = "_" + stem
    return stem


# --------------------------------------------------------------------------
# File type detection
# --------------------------------------------------------------------------

RESOURCE_EXTS = frozenset((
    ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".webp", ".dds",
    ".ogg", ".wav", ".mp3", ".ttf", ".otf",
))


def magic_ext(data):
    """Return a canonical extension guessed from the file signature."""
    if data[:8] == b"\x89PNG\r\n\x1a\n":
        return ".png"
    if data[:4] == b"OggS":
        return ".ogg"
    if data[:4] == b"RIFF":
        if data[8:12] == b"WAVE":
            return ".wav"
        if data[8:12] == b"WEBP":
            return ".webp"
    if data[:3] == b"ID3":
        return ".mp3"
    if data[:2] in (b"\xff\xfb", b"\xff\xf3", b"\xff\xf2", b"\xff\xfa"):
        return ".mp3"
    if data[:6] in (b"GIF87a", b"GIF89a"):
        return ".gif"
    if data[:2] == b"\xff\xd8":
        return ".jpg"
    if data[:2] == b"BM":
        return ".bmp"
    if data[:4] in (b"\x00\x01\x00\x00", b"true", b"ttcf", b"OTTO"):
        return ".ttf"
    if data[:4] == b"DDS ":
        return ".dds"
    return ""


# --------------------------------------------------------------------------
# Path references
# --------------------------------------------------------------------------

def split_ref_prefix(token):
    """Split SHADOW:/ROOT: prefixes off a reference, as the engine does."""
    prefix = ""
    rest = token
    if rest.startswith("SHADOW:"):
        prefix = "SHADOW:"
        rest = rest[len("SHADOW:"):]
    if rest.startswith("ROOT:"):
        prefix += "ROOT:"
        rest = rest[len("ROOT:"):]
    return prefix, rest


def resolve_to_member(token, config_name, root, member_lower):
    """Resolve one reference token to the member it names, or None.

    Returns ``(prefix, original_member_name)``.  Built-in SHARED:/CORE:
    references are never rewritten, and values containing macros are left
    for --resolve to deal with.
    """
    token = token.strip()
    if not token or "${" in token:
        return None
    prefix, rest = split_ref_prefix(token)
    if rest.startswith(("SHARED:", "CORE:")):
        return None
    stripped = rest.replace("\\", "/").rstrip("/")
    if not stripped:
        return None
    if prefix.endswith("ROOT:"):
        bases = [root]
    else:
        curdir = config_name.rsplit("/", 1)[0] + "/" if "/" in config_name else ""
        bases = [curdir]
        parent = (curdir.rstrip("/").rsplit("/", 1)[0] + "/"
                  if "/" in curdir.rstrip("/") else "")
        if parent and parent != curdir:
            bases.append(parent)
        if root:
            bases.append(root)
    for base in bases:
        candidate = rt.normpath(base + stripped).lower()
        if candidate in member_lower:
            return prefix, member_lower[candidate]
    return None


def iter_refs(value, config_name, root, member_lower):
    """Yield every member referenced by one ini value."""
    if not value:
        return
    for part in value.split(","):
        got = resolve_to_member(part, config_name, root, member_lower)
        if got:
            yield got


# --------------------------------------------------------------------------
# Content-driven naming
# --------------------------------------------------------------------------

_DISPLAY_KEYS = ("displayText", "displayText_zh", "displayName", "name")


def pick_display(sections, file_name=""):
    """Best readable label inside a config's effective content."""
    if rt.is_modinfo(file_name):
        sections_ = [sections.get("mod") or {}]
    else:
        sections_ = [sections.get("core") or {}]
    for section in sections_:
        for key in _DISPLAY_KEYS:
            value = section.get(key)
            if not value:
                continue
            value = clean_text(value).strip()
            if (not value or "${" in value
                    or value.lower() in ("null", "none", "nil", "-1")):
                continue
            return value
    return None


def basename_stem(name):
    base = name.replace("\\", "/").rsplit("/", 1)[-1]
    return os.path.splitext(base)[0]


def build_plan(files, parsed, resolved, resolver, root, config_ext):
    """Assign a final, readable path to every member.

    Returns ``(plan, displays, owners, named, fallbacks)``:
        plan       original name -> new relative path
        displays   config name   -> readable label
        owners     member name   -> (referrer display, key) for resources
        named      how many members got a content-driven name
        fallbacks  how many members fell back to an escaped name
    """
    names = [n for n, _d, _c in files]
    member_lower = {}
    for n in names:
        member_lower.setdefault(n.lower(), n)
    config_order = [n for n in names if n in parsed]

    # -- readable label for every config -----------------------------------
    displays = {}
    for n in config_order:
        displays[n] = pick_display(resolved[n], n)

    # configs without their own name borrow the first unit that copies them
    target_user = {}
    for n in config_order:
        for target in rt._copyfrom_targets(parsed.get(n, {})):
            found = resolver.resolve_target(target, n)
            if found and found not in target_user:
                target_user[found] = n
    for _ in range(8):                    # follow base-of-base chains
        changed = False
        for n in config_order:
            if displays.get(n):
                continue
            user = target_user.get(n)
            if user and displays.get(user):
                displays[n] = displays[user] + "_base"
                changed = True
        if not changed:
            break

    # -- which config/key references each resource -------------------------
    owners = {}
    for n in config_order:
        label = displays.get(n) or basename_stem(n)
        for _section, kv in resolved[n].items():
            for key, value in kv.items():
                if key.startswith("@"):
                    continue
                for _prefix, target in iter_refs(value, n, root, member_lower):
                    if target == n:
                        continue
                    if target not in owners:
                        owners[target] = (label, key)

    # -- final paths --------------------------------------------------------
    plan = {}
    taken = set()

    def unique(path):
        if path.lower() not in taken:
            taken.add(path.lower())
            return path
        head, ext = os.path.splitext(path)
        i = 2
        while True:
            candidate = "%s_%d%s" % (head, i, ext)
            if candidate.lower() not in taken:
                taken.add(candidate.lower())
                return candidate
            i += 1

    template_index = 0
    named = 0
    fallbacks = 0
    for n, data, _changed in files:
        if n not in parsed:
            ext = magic_ext(data)
            if not ext:
                ext = os.path.splitext(n.replace("\\", "/"))[1].lower()
            if n in owners:
                label, key = owners[n]
                stem = sanitize_stem(label + "_" + key)
                named += 1
            else:
                stem = sanitize_stem(escaped_name(basename_stem(n)))
                fallbacks += 1
            folder = "resources" if ext in RESOURCE_EXTS else "misc"
            plan[n] = unique("%s/%s%s" % (folder, stem, ext))
            continue
        if rt.is_modinfo(n):
            plan[n] = unique("mod-info.txt")
            continue
        if rt.is_template_entry(n):
            template_index += 1
            folder = ("templates" if template_index == 1
                      else "templates_%d" % template_index)
            plan[n] = folder + "/" + rt.basename(n)
            continue

        if displays.get(n):
            stem = sanitize_stem(displays[n])
            named += 1
        else:
            stem = sanitize_stem(escaped_name(basename_stem(n)))
            fallbacks += 1
        source_ext = os.path.splitext(n.replace("\\", "/"))[1].lower()
        if config_ext == "keep":
            ext = source_ext
        else:
            ext = ".ini"
        folder = "units" if source_ext == ".ini" else "bases"
        plan[n] = unique("%s/%s%s" % (folder, stem, ext))

    return plan, displays, owners, named, fallbacks


# --------------------------------------------------------------------------
# Reference rewriting + content cleanup
# --------------------------------------------------------------------------

def rewrite_value(value, file_name, dest_dir, plan, root, member_lower):
    """Rewrite every member reference inside one value; clean the rest.

    Returns ``(new_value, changed_count)``.
    """
    if not value:
        return clean_text(value), 0
    parts = value.split(",")
    out = []
    changed = 0
    for part in parts:
        token = part.strip()
        got = resolve_to_member(token, file_name, root, member_lower)
        if not got:
            out.append(clean_text(part))
            continue
        prefix, target = got
        new = plan[target]
        if prefix:
            replacement = prefix + new
        elif dest_dir:
            replacement = posixpath.relpath(new, dest_dir)
        else:
            replacement = new
        if replacement != token:
            changed += 1
        out.append(replacement)
    return ",".join(out), changed


def rewrite_sections(sections, file_name, plan, root, member_lower):
    """Clean one config and rewrite its references for the new layout."""
    dest_dir = posixpath.dirname(plan[file_name])
    out = OrderedDict()
    changed = 0
    for section, kv in sections.items():
        name = clean_text(section).strip() or section
        dest = out.setdefault(name, OrderedDict())
        for key, value in kv.items():
            key = clean_text(key).strip() or key
            value, hits = rewrite_value(
                value, file_name, dest_dir, plan, root, member_lower)
            dest[key] = value
            changed += hits
    return out, changed


# --------------------------------------------------------------------------
# Main decompile step
# --------------------------------------------------------------------------

def console_text(text):
    """Make arbitrary Unicode safe for the current console encoding."""
    enc = getattr(sys.stdout, "encoding", None) or "utf-8"
    try:
        text.encode(enc)
        return text
    except (UnicodeEncodeError, LookupError):
        try:
            return text.encode(enc, "backslashreplace").decode(enc, "replace")
        except (UnicodeEncodeError, LookupError):
            return text.encode("ascii", "backslashreplace").decode("ascii")


def read_members(in_path, repair=False, progress=None):
    """Read all members, auto-switching to the repair reader if needed."""
    files = None
    repaired = False
    if not repair:
        try:
            zf = rt.open_zip(in_path)
            try:
                files, dirs = rt.collect(zf, progress)
            finally:
                zf.close()
        except Exception:
            files = None
    if files is None:
        files, dirs = rt.collect_repaired(in_path, progress)
        repaired = True
    return files, dirs, repaired


def decompile(in_path, out_dir, resolve=False, resolve_template=False,
              config_ext="ini", repair=False, list_only=False, progress=None):
    if resolve_template:
        resolve = True
    if progress is None:
        progress = rt.Progress()
    stats = {
        "files": 0,
        "disguised": 0,
        "repaired": False,
        "configs": 0,
        "units": 0,
        "bases": 0,
        "templates": 0,
        "named": 0,
        "escaped": 0,
        "refs": 0,
        "unresolved": 0,
        "empty_dirs": 0,
        "out_dir": out_dir,
    }

    files, dirs, stats["repaired"] = read_members(in_path, repair, progress)

    parsed, _ = rt.build_config_sections(
        files, False, resolve_template, progress)
    root = rt.detect_root([n for n, _d, _c in files])

    # build_config_sections() detects disguised configs only when they are
    # extensionless or reachable through copyFrom; protected packs may also
    # hide configs behind arbitrary extensions (e.g. .ogg).  A decoder plus
    # the "recognised section" requirement keeps binaries from matching.
    by_name = {n: d for n, d, _c in files}
    finder = rt.Resolver(parsed, root, resolve_template)
    finder.index = rt.FileIndex([n for n, _d, _c in files])
    work = []
    for name, data, _c in files:
        if name in parsed or rt.is_text_config(name):
            continue
        sections = rt._as_config(name, data, require_known=True)
        if sections is not None:
            parsed[name] = sections
            work.append(name)
    while work:
        name = work.pop()
        for target in rt._copyfrom_targets(parsed[name]):
            target_name = finder.resolve_target(target, name)
            if not target_name or target_name in parsed:
                continue
            sections = rt._as_config(
                target_name, by_name.get(target_name, b""))
            if sections is not None:
                parsed[target_name] = sections
                work.append(target_name)

    resolver = rt.Resolver(parsed, root, resolve_template)

    if progress:
        progress.phase("解析", len(parsed))
    resolved = OrderedDict()
    for name in parsed:
        resolved[name] = resolver.resolve(name)
        if progress:
            progress.step()

    plan, _displays, _owners, named, fallbacks = build_plan(
        files, parsed, resolved, resolver, root, config_ext)
    stats["named"] = named
    stats["escaped"] = fallbacks
    member_lower = {}
    for name in plan:
        member_lower.setdefault(name.lower(), name)

    if list_only:
        for name, data, _changed in files:
            print("%10d  %s  ->  %s"
                  % (len(data), console_text(name), console_text(plan[name])))
        progress.finish()
        return stats

    os.makedirs(out_dir, exist_ok=True)
    if progress:
        progress.phase("写出", len(files))
    for name, data, changed in files:
        if changed:
            stats["disguised"] += 1
        if name in parsed:
            if resolve_template and rt.is_template_entry(name):
                stats["templates"] += 1
                if progress:
                    progress.step()
                continue
            sections = resolved[name] if resolve else parsed[name]
            sections, hits = rewrite_sections(
                sections, name, plan, root, member_lower)
            stats["refs"] += hits
            data = rt.dump_ini(sections).encode("utf-8")
            stats["configs"] += 1
            if rt.is_template_entry(name):
                stats["templates"] += 1
            elif rt.is_modinfo(name):
                pass
            elif plan[name].startswith("units/"):
                stats["units"] += 1
            else:
                stats["bases"] += 1
            if resolve and b"${" in data:
                stats["unresolved"] += 1
        dest = rt.safe_member_path(out_dir, plan[name])
        parent = os.path.dirname(dest)
        if parent:
            os.makedirs(parent, exist_ok=True)
        with open(dest, "wb") as fh:
            fh.write(data)
        stats["files"] += 1
        if progress:
            progress.step()

    stats["empty_dirs"] = len(dirs)
    progress.finish()
    return stats


# --------------------------------------------------------------------------
# Self test
# --------------------------------------------------------------------------

def selftest():
    tmp = tempfile.mkdtemp(prefix="rwdec_")
    try:
        zip_path = os.path.join(tmp, "t.rwmod")
        out_dir = os.path.join(tmp, "out")
        png = b"\x89PNG\r\n\x1a\n" + b"\x00" * 32
        base = "[core]\nprice:10\n"
        unit = ("[core]\n"
                "copyFrom: ROOT:mod/basecfg/\n"
                "displayText: TankUnit\n"
                "name: t1\n"
                "[graphics]\n"
                "image: ROOT:mod/pic1/\n")
        with zipfile.ZipFile(zip_path, "w") as zf:
            zf.writestr("mod/basecfg/", base)   # disguised config base
            zf.writestr("mod/pic1/", png)       # disguised image
            zf.writestr("mod/t1.ini", unit)
            zf.writestr("mod/raw.bin", png)     # unreferenced image

        stats = decompile(zip_path, out_dir,
                          progress=rt.Progress(enabled=False))

        expected = [
            os.path.join(out_dir, "units", "TankUnit.ini"),
            os.path.join(out_dir, "bases", "TankUnit_base.ini"),
            os.path.join(out_dir, "resources", "TankUnit_image.png"),
            os.path.join(out_dir, "resources", "raw.png"),
        ]
        for path in expected:
            if not os.path.isfile(path):
                print("SELFTEST FAILED (missing %s)" % path)
                return 1
        text = open(expected[0], "rb").read().decode("utf-8")
        if "ROOT:resources/TankUnit_image.png" not in text:
            print("SELFTEST FAILED (image ref): %r" % text)
            return 1
        if "ROOT:bases/TankUnit_base.ini" not in text:
            print("SELFTEST FAILED (copyFrom ref): %r" % text)
            return 1
        base_text = open(expected[1], "rb").read().decode("utf-8")
        if "price:10" not in base_text:
            print("SELFTEST FAILED (base content): %r" % base_text)
            return 1
        if stats["units"] != 1 or stats["bases"] != 1:
            print("SELFTEST FAILED (stats): %r" % stats)
            return 1

        # obfuscation cleanup + escaped fallback must stay unique
        if clean_text("\u200bco\u202ere") != "core":
            print("SELFTEST FAILED (clean_text section)")
            return 1
        dirty = rt.parse_ini("[\u200bco\u202ere]\rna\u2066me: Ta\u200bnk\r")
        cleaned = OrderedDict(
            (clean_text(sec), OrderedDict(
                (clean_text(k), clean_text(v)) for k, v in kv.items()))
            for sec, kv in dirty.items())
        if (list(cleaned) != ["core"]
                or list(cleaned["core"]) != ["name"]
                or cleaned["core"]["name"] != "Tank"):
            print("SELFTEST FAILED (parse obfuscated)")
            return 1
        if escaped_name("\u202e\U000e0d81") != "x202e_xe0d81_":
            print("SELFTEST FAILED (escaped_name)")
            return 1
        print("SELFTEST OK")
        return 0
    finally:
        import shutil
        shutil.rmtree(tmp, ignore_errors=True)


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Decompile a Rusted Warfare .rwmod into a readable "
                    "source tree (content-driven file names).")
    ap.add_argument("input", nargs="?", help="input .rwmod / .zip / .apk")
    ap.add_argument("-o", "--out-dir", default=None,
                    help="output folder (default: <input>_decompiled next "
                         "to the input file)")
    ap.add_argument("--config-ext", choices=("ini", "keep"), default="ini",
                    help="extension for config files: 'ini' renames every "
                         "config to .ini (readable; default), 'keep' keeps "
                         "the original extension (extensionless stays "
                         "extensionless)")
    ap.add_argument("--resolve", action="store_true",
                    help="write the fully expanded (copyFrom / ${...} "
                         "inlined) content instead of the normalized "
                         "original")
    ap.add_argument("--resolve-template", action="store_true",
                    help="also inline all-units.template into each unit and "
                         "drop the template files (implies --resolve)")
    ap.add_argument("--repair", action="store_true",
                    help="force the repair reader for zips with mangled "
                         "header fields (automatic when the normal reader "
                         "fails)")
    ap.add_argument("--list", action="store_true",
                    help="only print the old -> new name mapping")
    ap.add_argument("--no-progress", action="store_true",
                    help="disable the progress bar")
    ap.add_argument("--selftest", action="store_true",
                    help="run the built-in test and exit")
    args = ap.parse_args(argv)

    if args.selftest:
        return selftest()
    if not args.input:
        ap.print_help()
        return 2
    if not os.path.isfile(args.input):
        print("input not found: %s" % args.input, file=sys.stderr)
        return 2

    out_dir = args.out_dir
    if out_dir is None and not args.list:
        base = os.path.splitext(os.path.basename(args.input))[0]
        out_dir = os.path.join(
            os.path.dirname(os.path.abspath(args.input)),
            base + "_decompiled")

    try:
        stats = decompile(
            args.input,
            out_dir=out_dir,
            resolve=args.resolve or args.resolve_template,
            resolve_template=args.resolve_template,
            config_ext=args.config_ext,
            repair=args.repair,
            list_only=args.list,
            progress=rt.Progress(enabled=(False if args.no_progress else None)),
        )
    except zipfile.BadZipFile:
        print("error: %s is not a valid zip/rwmod" % args.input,
              file=sys.stderr)
        return 1
    except BrokenPipeError:
        # Piping --list into a command that stops reading early (e.g.
        # `--list | Select-Object -First 5`) must not raise at shutdown.
        sys.stdout = open(os.devnull, "w")
        return 0
    except (OSError, ValueError) as exc:
        print("error: %s" % exc, file=sys.stderr)
        return 1

    if args.list:
        return 0

    print("files written      : %d" % stats["files"])
    if stats["repaired"]:
        print("zip header repair  : yes")
    print("disguised names fix: %d" % stats["disguised"])
    print("configs decompiled : %d (units %d, bases %d, templates %d)"
          % (stats["configs"], stats["units"], stats["bases"],
             stats["templates"]))
    print("names from content : %d" % stats["named"])
    print("escaped fallbacks  : %d" % stats["escaped"])
    if stats["refs"]:
        print("references rewritten: %d" % stats["refs"])
    if args.resolve:
        print("unresolved macros  : %d file(s)" % stats["unresolved"])
    if stats["empty_dirs"]:
        print("empty folders      : %d ignored" % stats["empty_dirs"])
    print("output folder      : %s" % console_text(stats["out_dir"]))
    return 0


if __name__ == "__main__":
    print('版本信息：  '+VERSION)
    sys.exit(main())
